// This file is generated by running 'flutter pub run build_runner build'
import 'package:freezed_annotation/freezed_annotation.dart';

import '../domain/mind_map.dart';

part 'mind_map_model.freezed.dart';
part 'mind_map_model.g.dart';

@freezed
class MindMapNodeModel extends MindMapNode with _$MindMapNodeModel {
  const factory MindMapNodeModel({
    required String name,
    required List<MindMapNodeModel> children,
    String? description,
    String? image,
    String? excerpt,
  }) = _MindMapNodeModel;

  // A factory constructor that initializes an instance from a JSON map.
  factory MindMapNodeModel.fromJson(Map<String, dynamic> json) =>
      _$MindMapNodeModelFromJson(json);
}

@freezed
class MindMapModel extends MindMap with _$MindMapModel {
  const factory MindMapModel({
    required String name,
    required MindMapNodeModel rootNode,
    String? caption,
  }) = _MindMapModel;

  factory MindMapModel.fromJson(Map<String, dynamic> json) =>
      _$MindMapModelFromJson(json);
}
