import 'package:freezed_annotation/freezed_annotation.dart';

import '../../lesson/data/model/lesson_model.dart';
import '../domain/unit_entity.dart';

// This files will be generated by running 'flutter pub run build_runner build'
part 'unit_model.freezed.dart';
part 'unit_model.g.dart';

@freezed
class UnitModel extends UnitEntity with _$UnitModel {
  const factory UnitModel({
    required String name,
    required List<LessonModel> lessons,
    String? description,
  }) = _UnitModel;

  factory UnitModel.fromJson(Map<String, dynamic> json) =>
      _$UnitModelFromJson(json);
}
