import 'package:freezed_annotation/freezed_annotation.dart';

import '../../domain/course_entity.dart';
import 'subject_model.dart';

// This files will be generated by running 'flutter pub run build_runner build'
part 'course_model.freezed.dart';
part 'course_model.g.dart';

@freezed
class CourseModel extends CourseEntity with _$CourseModel {
  factory CourseModel({
    required String title,
    List<SubjectModel>? subjects,
  }) = _CourseModel;

  factory CourseModel.fromJson(Map<String, dynamic> json) =>
      _$CourseModelFromJson(json);
}
