import 'package:freezed_annotation/freezed_annotation.dart';

import '../../domain/subject_entity.dart';
import 'unit_model.dart';

// This files will be generated by running 'flutter pub run build_runner build'
part 'subject_model.freezed.dart';
part 'subject_model.g.dart';

@freezed
class SubjectModel extends SubjectEntity with _$SubjectModel {
  factory SubjectModel({
    required String name,
    required String imageUrl,
    List<UnitModel>? units,
  }) = _SubjectModel;

  factory SubjectModel.fromJson(Map<String, dynamic> json) =>
      _$SubjectModelFromJson(json);
}
