// This file is generated by running 'flutter pub run build_runner build'
import 'package:freezed_annotation/freezed_annotation.dart';

part 'mind_map.freezed.dart';
part 'mind_map.g.dart';

@freezed
class MindMapNode with _$MindMapNode {
  const factory MindMapNode({
    required String name,
    required List<MindMapNode> children,
    String? description,
    String? image,
    String? excerpt,
  }) = _MindMapNode;

  // A factory constructor that initializes an instance from a JSON map.
  factory MindMapNode.fromJson(Map<String, dynamic> json) =>
      _$MindMapNodeFromJson(json);
}

@freezed
class MindMap with _$MindMap {
  const factory MindMap(
      {required String name,
      required MindMapNode rootNode,
      String? caption}) = _MindMap;

  factory MindMap.fromJson(Map<String, dynamic> json) =>
      _$MindMapFromJson(json);
}
